[project]
name = "bpmn-ged"
version = "0.1.0"
description = "A tool to compare BPMN diagrams using (relative) graph edit distance"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networkx>=3.4.2",
    "numpy>=2.2.0",
    "scipy>=1.14.1",
]
