[project]
name = "bpmn-ged"
version = "0.1.0"
description = "A tool to compare BPMN diagrams using graph edit distance"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.57.4",
]
